version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wasted
      POSTGRES_DB: JwtTestTask
    ports:
      - "5431:5432"
    volumes:
      - jwt_task_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: wasted
      DB_NAME: JwtTestTask
      DB_PORT: 5432
      SERVER_PORT: :8080
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  jwt_task_data:

